version: "3.9"

services:
  postgres:
    image: postgres:18-alpine
    container_name: visvire-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: visvire
      POSTGRES_PASSWORD: visvire123
      POSTGRES_DB: visvire_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
